# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: "Painel de indicadores"
author: "Secretaria da Fazenda / Setor de Contabilidade"
copyright: "2023"
logo: assets/images/brasao.jpg
exclude_patterns: [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints", "README.*", "capa-*.ipynb"]

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

html:
  favicon: assets/images/brasao.ico
  use_edit_page_button: false
  use_repository_button: false
  use_issues_button: false
  home_page_in_navbar: true
  baseurl: "https://iddrs.github.io/iddrs-kpi/"
  announcement: "Esta é uma versão em desenvolvimento. Encontrou um erro? Contate o desenvolvedor <everton3x@gmail.com>"

parse:
  myst_substitutions:
    data_base: "Abril de 2023"
  myst_enable_extensions:
    - colon_fence
    - dollarmath
    - linkify
    - substitution
    - tasklist

# Define the name of the latex output file for PDF builds
# latex:
#   latex_documents:
#     targetname: book.tex

# Add a bibtex file so that we can create citations
# bibtex_bibfiles:
#   - assets/references.bib

# Information about where the book exists on the web
# repository:
#   url: https://github.com/executablebooks/jupyter-book  # Online location of your book
#   path_to_book: docs  # Optional path to your book, relative to the repository root
#   branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
# html:
#   use_issues_button: true
#   use_repository_button: true
